DROP DATABASE IF EXISTS AGAPE_DB; 

CREATE DATABASE AGAPE_DB;

USE AGAPE_DB;

CREATE TABLE IF NOT EXISTS TB_CIDADE(
CD_CIDADE INT NOT NULL AUTO_INCREMENT,
NM_CIDADE VARCHAR (40),
NM_ESTADOS VARCHAR (80),
CONSTRAINT PK_CIDADE
	PRIMARY KEY (CD_CIDADE)
    )
	ENGINE INNODB;

CREATE TABLE IF NOT EXISTS TB_USERS (
    CD_USER INT AUTO_INCREMENT,
    TIPO_USER VARCHAR(10),
    LOGIN VARCHAR(80),
    SENHA VARCHAR(128),
    PRIMARY KEY (CD_USER)
) AUTO_INCREMENT=100;

CREATE TABLE IF NOT EXISTS TB_ONG (
CD_ONG INT NOT NULL AUTO_INCREMENT,
CD_CIDADE INT,
NM_ONG VARCHAR(80),
NM_REPRESENTANTE VARCHAR(80),
EMAIL VARCHAR(90),
CNPJ CHAR (19),
SENHA VARCHAR(128),
SOBRE TEXT,
PIC LONGBLOB,
INSTA VARCHAR(45),
WPP VARCHAR(15),
TWITTER VARCHAR(45),
CONSTRAINT PK_ONG PRIMARY KEY(CD_ONG))
AUTO_INCREMENT=100
ENGINE INNODB;
    
CREATE TABLE IF NOT EXISTS TB_DOADOR (
CD_DOADOR INT AUTO_INCREMENT,
CD_USER INT,
CD_ONG INT,
NM_DOADOR VARCHAR(80),
NM_USER VARCHAR(80),
DOCUMENTO CHAR(19),
SENHA VARCHAR(128),
EMAIL VARCHAR(90),
CONSTRAINT PK_DOADOR
	PRIMARY KEY(CD_DOADOR))
    AUTO_INCREMENT=100
ENGINE INNODB;


CREATE TABLE IF NOT EXISTS TB_CATEGORIA(
CD_CATEGORIA INT NOT NULL,
NM_DESCRICAO VARCHAR(30),
CONSTRAINT PK_CATEGORIA
	PRIMARY KEY(CD_CATEGORIA)
    )
ENGINE INNODB;


CREATE TABLE IF NOT EXISTS TB_RESOLUCAO(
CD_RESOLUCAO INT NOT NULL,
CD_ONG INT NOT NULL,
CD_CATEGORIA INT NOT NULL,
    
CONSTRAINT PK_RESOLUCAO
	PRIMARY KEY(CD_RESOLUCAO)    
    )
    ENGINE INNODB;


CREATE TABLE IF NOT EXISTS TB_POST(
CD_POST INT NOT NULL,
CD_ONG INT NOT NULL,
TEXTO_POST TEXT,
CONSTRAINT PK_POSTAGEM
	PRIMARY KEY(CD_POST)
)
ENGINE INNODB;

CREATE TABLE IF NOT EXISTS TB_COMENT(
CD_COMENT INT NOT NULL AUTO_INCREMENT,
CD_POST INT,
CD_DOADOR INT,
TEXTO_COMENT TEXT,
CONSTRAINT PK_COMENT
	PRIMARY KEY(CD_COMENT))
ENGINE INNODB;

CREATE TABLE IF NOT EXISTS TB_REACAO(
CD_REACAO INT NOT NULL AUTO_INCREMENT,
CD_POST INT,
CD_DOADOR INT,
CONSTRAINT PK_REACAO
	PRIMARY KEY(CD_REACAO)
)
ENGINE INNODB;