-- SALVANDO NO PADRÃO PTCC 02052023 1400
DROP DATABASE IF EXISTS AGAPE_DB; 

CREATE DATABASE AGAPE_DB;

USE AGAPE_DB;

CREATE TABLE IF NOT EXISTS TB_ONG (
    CD_ONG INT NOT NULL AUTO_INCREMENT,
    NM_ONG VARCHAR(30),
    NM_REPRESENTANTE VARCHAR(80),
    EMAIL VARCHAR(90),
    CNPJ CHAR (19),
    SENHA VARCHAR(128),
    SOBRE VARCHAR (512),
    PIC LONGBLOB,
    INSTA VARCHAR(45),
    WPP VARCHAR(15),
    TWITTER VARCHAR(45),
    CONSTRAINT PK_ONG PRIMARY KEY(CD_ONG)
) AUTO_INCREMENT=100;

CREATE TABLE IF NOT EXISTS TB_CIDADE(
    CD_CIDADE INT NOT NULL AUTO_INCREMENT,
    CD_ONG INT NOT NULL,
    NM_CIDADE VARCHAR (40),
    NM_ESTADOS VARCHAR (80),
    PRIMARY KEY (CD_CIDADE),
    FOREIGN KEY (CD_ONG) REFERENCES TB_ONG (CD_ONG)
);

CREATE TABLE IF NOT EXISTS TB_USERS (
    CD_USER INT AUTO_INCREMENT,
    TIPO_USER VARCHAR(10),
    LOGIN VARCHAR(80),
    SENHA VARCHAR(128),
    PRIMARY KEY (CD_USER)
) AUTO_INCREMENT=100;

CREATE TABLE IF NOT EXISTS TB_DOADOR (
    CD_DOADOR INT AUTO_INCREMENT,
    CD_USER INT,
    CD_ONG INT,
    NM_DOADOR VARCHAR(80),
    NM_USER VARCHAR(80),
    DOCUMENTO CHAR(19),
    SENHA VARCHAR(128),
    EMAIL VARCHAR(90),
    PRIMARY KEY(CD_DOADOR),
    FOREIGN KEY (CD_USER) REFERENCES TB_USERS(CD_USER)
) AUTO_INCREMENT=100;

CREATE TABLE IF NOT EXISTS TB_CATEGORIA(
    CD_CATEGORIA INT NOT NULL,
    CD_ONG INT NOT NULL,
    CRIANCA BOOL,
    IDOSOS BOOL,
    ANIMAIS BOOL,
    SAUDE BOOL,
    AMBIENTAL BOOL,
    ALIMENTOS BOOL,
    AFRO BOOL,
    COMUNIDADES BOOL,
    PRIMARY KEY(CD_CATEGORIA),
    FOREIGN KEY (CD_ONG) REFERENCES TB_ONG (CD_ONG)
);

CREATE TABLE IF NOT EXISTS TB_POST(
    CD_POST INT NOT NULL,
    CD_ONG INT NOT NULL,
    TEXTO_POST VARCHAR(600),
    PRIMARY KEY(CD_POST),
    FOREIGN KEY (CD_ONG) REFERENCES TB_ONG (CD_ONG)
);

CREATE TABLE IF NOT EXISTS TB_COMENT(
    CD_COMENT INT NOT NULL,
    CD_POST INT NOT NULL,
    CD_DOADOR INT NOT NULL,
    TEXTO_COMENT VARCHAR(600),
    PRIMARY KEY(CD_COMENT),
    FOREIGN KEY (CD_POST) REFERENCES TB_POST (CD_POST)
);

CREATE TABLE IF NOT EXISTS TB_REACAO(
    CD_REACAO INT NOT NULL,
    CD_POST INT NOT NULL,
    CD_DOADOR INT NOT NULL,
    PRIMARY KEY(CD_REACAO),
    FOREIGN KEY (CD_POST) REFERENCES TB_POST (CD_POST)
);
